# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autopay', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-monthly_budget',),
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spending_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('human', models.CharField(choices=[('Laurel', 'Laurel'), ('Cody', 'Cody')], max_length=20)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget', verbose_name='Category')),
            ],
            options={
                'ordering': ('-spending_date',),
            },
        ),
    ]
