# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('-monthly_budget',), 'verbose_name': 'Budget item', 'verbose_name_plural': 'Budget items'},
        ),
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ('-spending_date',), 'verbose_name': 'Spending', 'verbose_name_plural': 'Spending'},
        ),
        migrations.AddField(
            model_name='spending',
            name='recipient',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
