# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20160509_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='human',
            field=models.CharField(choices=[('Laurel', 'Laurel'), ('Cody', 'Cody'), ('Both', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spending',
            name='spending_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
