# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20160516_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ('name',)},
        ),
    ]
