# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20160516_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
