# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_spending_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('category',), 'verbose_name': 'Budget item', 'verbose_name_plural': 'Budget items'},
        ),
    ]
