# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20160516_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 8, 0, 45, 46, 908000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
