# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_spending_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('human', models.CharField(choices=[('Laurel', 'Laurel'), ('Cody', 'Cody'), ('Both', 'Both')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-income_date',),
                'verbose_name': 'Incoming payment',
                'verbose_name_plural': 'Incoming payments',
            },
        ),
    ]
