# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-01 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20160614_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
