# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20161001_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Spending')),
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
