# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-13 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20161213_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexpense',
            name='spending',
        ),
        migrations.AddField(
            model_name='spending',
            name='major_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.MajorExpense'),
        ),
    ]
