# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20161213_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='major_expense',
        ),
        migrations.DeleteModel(
            name='MajorExpense',
        ),
    ]
